---
title: "plot_reconstruction"
author: "Kelsey Ogren"
date: "2024-09-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

---
title: "Recreating_graph"
author: "Kelsey Ogren"
date: "2024-09-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggplot2)

dat.base <- read.delim2(file="injurydat.txt", header=T, sep="\t")
#dat.base
#dat.base %>% select(Victim.injury) %>% rename("injured" == "Injured")
#mydat$Sex[mydat$Sex %in% c("f", "female")] <- "F"

#######exploring different reconstruction plot ideas#######
dat.base$Victim.injury[dat.base$Victim.injury %in% c("injured", "Injured")] <- "injured"

NSW_data <- dat.base %>% filter(State == "NSW") %>% subset(select= c(Incident.year, Victim.injury, Shark.common.name))

NSW_data %>% filter(Incident.year > 1869) %>% ggplot(aes(x= Incident.year)) +
  geom_freqpoly(aes(color= Victim.injury)) +
  scale_x_continuous(breaks= seq(1870, 2020, 10))
  
NSW_data %>% filter(Incident.year > 1869) %>% ggplot(aes(x= Incident.year)) +
  geom_histogram(aes(fill= Victim.injury), position= "dodge", binwidth = 3) +
  scale_x_continuous(breaks= seq(1870, 2020, 10))

dat.base %>% filter(State == "NSW") %>% ggplot(aes(x= Incident.year)) +
  geom_histogram(aes(fill= Victim.injury), position= "dodge")
```








```{r}
dat.base$Victim.injury[dat.base$Victim.injury %in% c("injured", "Injured")] <- "Injury"
dat.base$Victim.injury[dat.base$Victim.injury %in% c("fatal")] <- "Fatality"
dat.base$Victim.injury[dat.base$Victim.injury %in% c("uninjured")] <- "Uninjured"

NSW_data <- dat.base %>% filter(State == "NSW") %>% subset(select= c(Incident.year, Victim.injury, Shark.common.name))





library(tidyverse)
library(ggplot2)

#######Final reconstructed plot#######
NSW_data %>% filter(Incident.year > 1870) %>% ggplot(aes(x= Incident.year)) +
  geom_freqpoly(aes(color= Victim.injury), bins= 50) +
  scale_x_continuous(breaks= seq(1870, 2020, 10)) +
  theme_bw() +
  labs(title= "NSW Shark Encounters", x= "Year", y= "Number of Incidents") +
  theme(axis.title= element_text(size= 18), 
        (panel.grid.minor.x = element_blank())) +
  theme(plot.title= element_text(size= 25,hjust= 0.5)) +
  theme(legend.title = element_blank(),
        legend.text=element_text(size=15)) +
  theme(panel.grid.minor.x = element_blank()) +
  theme(axis.text= element_text(size=12))
  


```