---
title: "QFISH assignment"
author: "Kelsey Ogren"
date: "2024-09-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


##Data Wrangling and Cleaning

```{r data_wrangling}
library(janitor)
library(tidyverse)
shark_program <-
  read_csv("export.csv") |>
  row_to_names(row_number = 2, remove_rows_above = FALSE) |> #variable names are meaningless, so change by instructing 'row_to_names' function to put row number 2 as the name
  clean_names() 
head(shark_program)

shark_program_fatality <-
  read_csv("export2.csv") |>
  row_to_names(row_number = 3, remove_rows_above = FALSE) |> #variable names are meaningless, so change by instructing 'row_to_names' function to put row number 2 as the name
  clean_names() 
head(shark_program_fatality)

```

```{r fatality_species}
library(tidyverse)
library(dplyr)
library(janitor)

dead_data <-
  shark_program_fatality |>
  select(area | contains("dead")) |>
  row_to_names(row_number= 2, remove_rows_above = FALSE) |>
  clean_names() |>
  rename(Area = 1)


live_data <-
   shark_program_fatality |>
  select(area | contains("alive")) |>
  row_to_names(row_number= 2, remove_rows_above = FALSE) |>
  clean_names() |>
  rename(Area = 1)

######shark dead data
shark_dead <- 
  dead_data |>
  select(Area | contains("shark")) |>
  row_to_names(row_number= 1) |>
  rename(Area = 1) |>
  mutate(across(-c(Area), as.numeric))

shark_alive <-
  live_data |>
  select(Area | contains("shark")) |>
  row_to_names(row_number= 1) |>
  rename(Area = 1) |>
  mutate(across(-c(Area), as.numeric))

turtle_dead <- 
  dead_data |>
  select(Area | contains("turtle")) |>
  row_to_names(row_number= 1) |>
  rename(Area = 1) |>
  mutate(across(-c(Area), as.numeric))

mammal_dead <-
  dead_data |>
  select(Area | contains("mammal")) |>
  row_to_names(row_number= 1) |>
  rename(Area = 1) |>
  mutate(across(-c(Area), as.numeric))


#### Pivoting Wide Tibbles into Long Format
long_shark_dead <- shark_dead |> 
  pivot_longer(!Area, names_to= "Year", values_to = "dead_sharks")

long_turtle_dead <- turtle_dead |> 
  pivot_longer(!Area, names_to= "Year", values_to = "dead_turtles")

long_mammal_dead <- mammal_dead |> 
  pivot_longer(!Area, names_to= "Year", values_to = "dead_mammals")

dead_animal <- left_join(long_shark_dead, long_turtle_dead)
dead_animals <- left_join(dead_animal, long_mammal_dead) |>
  mutate(Year = as.numeric(Year))

dead_shark_by_year <- long_shark_dead |>
  filter(Area == "Grand Total") |>
  mutate(Year = as.numeric(Year))

long_shark_catch <- shark_catch |> 
  pivot_longer(!Area, names_to= "Year", values_to = "Nos")

long_shark_catch_dead <- left_join(long_shark_catch, long_shark_dead) |>
  mutate(Year = as.numeric(Year))
```


```{r separating_species}
library(tidyverse)
library(dplyr)
#install.packages("janitor")
library(janitor)

mammal_catch <-
  shark_program |>
  select(area | contains("mammal")) |>
  row_to_names(row_number= 1) |>
  rename(Area = 1) |>
  mutate(across(-c(Area), as.numeric))

shark_catch <-
  shark_program |>
  select(area | contains("shark")) |>
  row_to_names(row_number= 1) |>
  rename(Area = 1) |>
  mutate(across(-c(Area), as.numeric))

turtle_catch <-
  shark_program |>
  select(area | contains("turtle")) |>
  row_to_names(row_number= 1) |>
  rename(Area = 1) |>
  mutate(across(-c(Area), as.numeric))

other_catch <-
  shark_program |>
  select(area | contains("other")) |>
  row_to_names(row_number= 1) |>
  rename(Area = 1) |>
  mutate(across(-c(Area), as.numeric))
```

## Pivoting Wide Tibbles into Long Format
```{r pivot_long}
long_shark_catch <- shark_catch |> 
  pivot_longer(!Area, names_to= "Year", values_to = "Nos")

long_mammal_catch <- mammal_catch |>
  pivot_longer(!Area, names_to= "Year", values_to = "Nos")

long_turtle_catch <- turtle_catch |>
  pivot_longer(!Area, names_to= "Year", values_to= "Nos")
```

## Making Stats
```{r stats}
shark_stats <-
  long_shark_catch |> #uses the long tibble
  filter(Area != "Grand Total") |> #filters out areas not including grandtotal
  group_by(Year) |> #groups area and numbers by year
  summarise(Mean =mean(Nos, na.rm= TRUE),
            SD = sd(Nos, na.rm= TRUE)) |> #calculates the statistics based on the year groupings
  mutate(Year = as.numeric(Year)) |> #makes the Year a numeric value
  mutate(Taxa= "Sharks") #creates new column with taxa as sharks

turtle_stats <-
  long_turtle_catch |>
  filter(Area != "Grand Total") |>
  group_by(Year) |>
  summarise(Mean = mean(Nos, na.rm= TRUE), 
            SD = sd(Nos, na.rm = TRUE)) |>
  mutate(Year = as.numeric(Year)) |>
  mutate(Taxa= "Turtles")

mammal_stats <-
  long_mammal_catch |>
  filter(Area != "Grand Total") |>
  group_by(Year) |>
  summarise(Mean = mean(Nos, na.rm= TRUE),
            SD= sd(Nos, na.rm= TRUE)) |>
  mutate(Year= as.numeric(Year)) |>
  mutate(Taxa= "Mammals")

combine_stats <-
  bind_rows(shark_stats, turtle_stats, mammal_stats)
```


```{r graphing}
library(ggplot2)

shark_catch_plot <- long_shark_catch_dead %>%
  filter(Area == "Grand Total") %>%
  ggplot() +
  geom_col(aes(x= Year, y= Nos), fill= "#00BA38") +
  geom_line(aes(x= Year, y= dead_sharks), color= "#F8766D") +
  geom_point(aes(x= Year, y= dead_sharks), color= "#F8766D")

shark_catch_plot

long_shark_catch_dead %>%
  filter(Area != "Grand Total") %>%
ggplot() +
  geom_col(aes(x= Year, y=Nos), fill= "#00BA38") +
  geom_col(aes(x= Year, y= dead_sharks), fill= "#F8766D")

#ggplot(data= combine_stats, aes(x= Year, y= Mean, fill= Taxa, shape= Taxa), color= "black") +
#  geom_line() +
#  geom_pointrange(aes(ymin= Mean - SD, ymax= Mean + SD)) +
#  scale_shape_manual(values= c(23, 24, 25))

ggplot(data= combine_stats, aes(x = Year, y= Mean, color= Taxa, shape= Taxa)) +
  geom_point() +
  geom_smooth() +
  theme_bw()
```



```{r}
long_shark_catch
long_shark_catch %>% filter(Area != "Grand Total") %>%
  filter(Nos > 50) %>%
  ggplot(aes(x= Year, y= Nos)) +
  geom_col(aes(fill= Area))

long_shark_catch %>% 
  filter(Area != "Grand Total") %>%
  ggplot(aes(x= Year, y= Nos, fill= Area))+
  geom_col(color= "white") 
#+ facet_wrap(~Area)


long_shark_catch %>% 
  filter(Area != "Grand Total") %>%
  ggplot(aes(x= Year, y= Nos, fill= Area))+
  geom_col() +
  theme_bw() +
  theme(axis.text.x = element_text(angle=45)) +
  scale_x_discrete(labels= c("01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24")) +
  facet_wrap(~Area) +
  labs(title = "Total Number of Sharks Caught by Area", y= "Number Caught") +
  theme(axis.title= element_text(size= 26), 
        (panel.grid.minor.x = element_blank())) +
  theme(plot.title= element_text(size= 35,hjust= 0.5)) +
  theme(panel.grid.minor.x = element_blank()) +
  theme(axis.text.y= element_text(size=18)) +
  theme(strip.text= element_text(size= 20)) +
  theme(legend.position = "none")
  
```

```{r GRAPH TO BE USED IN ASSIGNMENT IF IN R}
########## shark catches by area plot ###########
long_shark_catch %>% 
  filter(Area != "Grand Total") %>%
  ggplot(aes(x= Year, y= Nos, fill= Area))+
  geom_col() +
  theme_bw() +
  theme(axis.text.x = element_text(angle=45)) +
  scale_x_discrete(labels= c("01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24")) +
  facet_wrap(~Area) +
  labs(title = "Total Number of Sharks Caught by Area", y= "Number Caught") +
  theme(axis.text.x= element_text(size=5)) +
  theme(legend.position = "none")
```
```